# Generated by Django 5.0.3 on 2024-05-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='Work_time_en',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='Work_time_ru',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='Work_time_uz',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ReceptionDate_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ReceptionDate_ru',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ReceptionDate_uz',
        ),
    ]
