# Generated by Django 5.0.3 on 2024-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='product', verbose_name='Image')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': '3-Mahsulot rasmlari',
                'verbose_name_plural': 'B - 3-Mahsulot rasmlari',
            },
        ),
    ]
