# Generated by Django 5.0.3 on 2024-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0002_remove_companydetails_work_time_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiToken', models.CharField(max_length=255, verbose_name='Api Token')),
                ('chatID', models.CharField(max_length=255, verbose_name='Chat Id')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Telegram',
                'verbose_name_plural': 'G - Telegram',
            },
        ),
        migrations.AlterModelOptions(
            name='hamkor',
            options={'ordering': ['-Date'], 'verbose_name': 'Hamkor', 'verbose_name_plural': 'D - Hamkorlar'},
        ),
        migrations.AlterModelOptions(
            name='xabar',
            options={'ordering': ['-Checked'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'A - Xabarlar'},
        ),
    ]
