# Generated by Django 5.0.3 on 2024-06-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0003_remove_product_image_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsImportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=7)),
                ('measure', models.CharField(max_length=10, verbose_name='measure')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('summa', models.FloatField()),
                ('date', models.DateField(verbose_name='import date')),
                ('organisation', models.CharField(max_length=255, verbose_name='company name')),
                ('contract', models.FileField(blank=True, null=True, upload_to='Contracts')),
                ('comment', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importapp.product', verbose_name='Product name')),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'A - Export and Import stats',
            },
        ),
    ]
